Changelog for Hawaii release
sodafoundation/dashboard pull request #513
Opened 2021-01-07 19:18 UTC by kumarashit

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
 /kind new feature
> /kind bug fix
> /kind cleanup
> /kind revert change
> /kind design
> /kind documentation
> /kind enhancement

**What this PR does / why we need it**:
Changelog for hawaii release

**Which issue(s) this PR fixes**:

Fixes #

**Test Report Added?**:
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
> /kind TESTED
> /kind NOT-TESTED

**Test Report**:

**Special notes for your reviewer**:

2021-01-07 20:45 UTC, anvithks requested changes

2021-01-07 20:45 UTC, anvithks commented on CHANGELOG/CHANGELOG-v1.2.0.md
> +# Changelog since Greendlan(v1.1.0) release
Typo - > Greenland

2021-01-08 05:18 UTC, kumarashit commented on CHANGELOG/CHANGELOG-v1.2.0.md
> +# Changelog since Greendlan(v1.1.0) release
Fixed

2021-01-08 05:57 UTC, skdwriting approved these changes
LGTM

2021-01-08 06:03 UTC, anvithks approved these changes
LGTM

2021-01-08 06:04 UTC, merged